apiVersion: v1
kind: Secret
metadata:
  name: horizon-enterprise-license-defaults
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: horizon-platform
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  license-defaults.json: |
    {{- .Values.license | toJson | nindent 4 }}
