{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "horizon-license-management-service.secretName" . }}
  labels:
    {{- include "horizon-license-management-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  admin-api-key: {{ .Values.secrets.adminApiKey | quote }}
  signing-secret: {{ .Values.secrets.signingSecret | quote }}
  token-pepper: {{ .Values.secrets.tokenPepper | quote }}
{{- end }}
